name: Humble Package Build

on:
  push:
    branches: [ "humble" ]
  pull_request:
    branches: [ "humble" ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        cd ~/humble-vcan-image
        docker build -t humble-build .

    - name: Run colcon build
      run: |
        docker run --rm humble-build bash -c "source /opt/ros/humble/setup.bash && colcon build"

    - name: Run colcon test
      run: |
        docker run --rm humble-build bash -c "source /opt/ros/humble/setup.bash && colcon test"

    - name: Clean up
      run: |
        docker rmi humble-build
